# Generated by Django 4.2.29 on 2026-04-01 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('INCOME', 'INCOME'), ('EXPENSES', 'EXPENSES')], max_length=10)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Sales Revenue', 'Sales Revenue'), ('Software & Subscriptions', 'Software & Subscriptions'), ('Travel', 'Travel'), ('Refunds', 'Refunds'), ('Miscellaneous', 'Miscellaneous')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_note', models.TextField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
