# Generated by Django 4.2.29 on 2026-04-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'permissions': [('can_view_summary', 'Can view the aggregated dashboard summary')]},
        ),
    ]
