# Generated by Django 4.2.29 on 2026-04-02 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0002_alter_financialrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='user',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_staff', True), ('is_superuser', True), ('groups__name', 'Admin'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
